services:
  - type: web
    name: fm-core
    env: python
    plan: free
    branch: main  
    buildCommand: "./build.sh"
    startCommand: "gunicorn --workers 3 --bind 0.0.0.0:$PORT core.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        fromSecret: SECRET_KEY
      - key: DATABASE_URL
        fromSecret: DATABASE_URL
      - key: SIGNING_KEY
        fromSecret: SIGNING_KEY
      - key: SU_USERNAME
        fromSecret: SU_USERNAME
      - key: SU_EMAIL
        fromSecret: SU_EMAIL
      - key: SU_PASSWORD
        fromSecret: SU_PASSWORD
      - key: STAFF_USERNAME
        fromSecret: STAFF_USERNAME
      - key: STAFF_EMAIL
        fromSecret: STAFF_EMAIL
      - key: TEST_USER_EMAIL
        fromSecret: TEST_USER_EMAIL
      - key: CALLBACK_URL
        fromSecret: CALLBACK_URL
      - key: GOOGLE_CLIENT_ID
        fromSecret: GOOGLE_CLIENT_ID
      - key: GOOGLE_CLIENT_SECRET
        fromSecret: GOOGLE_CLIENT_SECRET
      - key: MAILGUN_API_KEY
        fromSecret: MAILGUN_API_KEY
      - key: MAILGUN_SENDER_DOMAIN
        fromSecret: MAILGUN_SENDER_DOMAIN
      - key: DEFAULT_FROM_EMAIL
        fromSecret: DEFAULT_FROM_EMAIL
      - key: SERVER_EMAIL
        fromSecret: SERVER_EMAIL
      - key: LOGIN_URL
        fromSecret: LOGIN_URL
      - key: REDIS_URL
        fromSecret: REDIS_URL
      - key: REDIS_PASSWORD
        fromSecret: REDIS_PASSWORD
      - key: EXPRESS_SERVICE_URL
        fromSecret: EXPRESS_SERVICE_URL
      - key: CORS_ALLOWED_ORIGINS
        fromSecret: CORS_ALLOWED_ORIGINS
      - key: CORS_ORIGIN_WHITELIST
        fromSecret: CORS_ORIGIN_WHITELIST
      - key: CSRF_TRUSTED_ORIGINS
        fromSecret: CSRF_TRUSTED_ORIGINS
      - key: SOCIAL_AUTH_ALLOWED_REDIRECT_URIS
        fromSecret: SOCIAL_AUTH_ALLOWED_REDIRECT_URIS
      - key: ALLOWED_HOSTS
        fromSecret: ALLOWED_HOSTS

   

  