name: CI - Test Django App

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations and seed data
        run: |
          python manage.py migrate --no-input

      - name: Run unit tests with coverage
        run: |
          pytest --cov --tb=short
