name: Django CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DEBUG: "True"
      SECRET_KEY: "ci-dummy-secret-key"
      SIGNING_KEY: "ci-dummy-signing-key"
      SU_USERNAME: "su-username"
      SU_EMAIL: "user100@grr.la"
      SU_PASSWORD: "fake-password"
      STAFF_USERNAME: "staff-username"
      STAFF_EMAIL: "user101@grr.la"
      TEST_USER_EMAIL: "user102@grr.la"
      DJANGO_SETTINGS_MODULE: "core.settings"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: pytest --cov --tb=short
