name: Django CI

on:
  push:
    branches:
      - main  # Run only on pushes to the main branch
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      # Use safe dummy values for CI/test
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"
      REDIS_URL: "redis://localhost:6379/1"
      REDIS_PASSWORD: ""
      SECRET_KEY: "test-secret"
      DEFAULT_FROM_EMAIL: "ci@example.com"
      SERVER_EMAIL: "ci@example.com"
      LOGIN_URL: "/auth/login/"
      CALLBACK_URL: "http://localhost:3000/callback"
      GOOGLE_CLIENT_ID: "fake-google-client-id"
      GOOGLE_CLIENT_SECRET: "fake-google-secret"
      MAILGUN_API_KEY: "fake-mailgun-key"
      MAILGUN_SENDER_DOMAIN: "fake.mailgun.org"
      CORS_ALLOWED_ORIGINS: "http://localhost:3000"
      CORS_ORIGIN_WHITELIST: "http://localhost:3000"
      SOCIAL_AUTH_ALLOWED_REDIRECT_URIS: "http://localhost:3000"
      CSRF_TRUSTED_ORIGINS: "http://localhost"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: pytest --cov --tb=short
